PREFIX ruim: <http://data.esante.gouv.fr/ansm/medicament/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT {
	?x rdfs:subClassOf [
		a owl:Restriction ;
		owl:onProperty ruim:contientFractionTherapeutique ;
		owl:someValuesFrom ?substance ;
	]
}
WHERE {
	?x ruim:fractionTherapeutique ?substance .
}